# Generated by Django 2.0.2 on 2018-03-20 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='datepulished',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 15, 13, 25, 123994)),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='lastedit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
