# Generated by Django 2.0.2 on 2018-03-23 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180323_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='ispublished',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='lastedit',
            new_name='last_edit',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='datepulished',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
