# Generated by Django 2.0.2 on 2018-03-20 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180320_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='datepulished',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 15, 19, 29, 110333)),
        ),
    ]
